# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "apps/backend/src/diesel_schema/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/run/media/verifiedfemboy/Disk/programming/react_x_rust/memorybyte/apps/backend/migrations"
