CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    nickname VARCHAR NOT NULL,
    name VARCHAR NOT NULL, 
    last_name VARCHAR NOT NULL, 
    email VARCHAR NOT NULL, 
    password VARCHAR NOT NULL, 
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);